{
    "name": "firerr",
    "version": "0.1.4",
    "description": "Catch Firebase Error From Asynchronous Functions",
    "main": "src/index.ts",
    "keywords": [
        "firebase",
        "error",
        "handling"
    ],
    "author": {
        "name": "qwyzex",
        "email": "qwyzex@yandex.com",
        "url": "https://github.com/qwyzex"
    },
    "license": "MIT",
    "publisher": "qwyzex",
    "homepage": "https://github.com/qwyzex/firerr",
    "bugs": {
        "url": "https://github.com/qwyzex/firerr/issues/new",
        "email": "xaliscoral@gmail.com"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/qwyzex/firerr"
    },
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
        "dev": "nodemon",
        "tsw": "tsc -w",
        "ts": "tsc"
    },
    "devDependencies": {
        "@types/node": "^17.0.13",
        "nodemon": "^2.0.15",
        "ts-node": "^10.4.0",
        "typescript": "^4.5.5"
    },
    "engines": {
        "node": ">=14.0.0"
    },
    "engineStrict": false,
    "dependencies": {
        "firebase": "^9.6.8"
    }
}
